image: node:10.15.3

pipelines:
  branches:
    development:
      - step:
          caches:
            - node
          script:
            - ssh -tt bitbucket-livechat@34.87.91.154<<EOF
              sudo -s
              /vnlp/bitbucket/livechat.sh
              exit
              exit
              EOF
    beta:
      - step:
          caches:
            - node
          script:
            - ssh -tt bitbucket-livechat@34.87.94.31<<EOF
              sudo -s
              /vnlp/bitbucket/livechat.sh
              exit
              exit
              EOF

