image: atlassian/default-image:2

pipelines:
  branches:
    dev:
      - step:
          name: "Build and push"
          script:
            - ssh -p 2201 root@113.176.195.87<<EOF
              /root/emandai/cmd/deploy-server.sh dev livechat ${BITBUCKET_BUILD_NUMBER}
              exit
              exit
              EOF
              EOF
      - step:
          name: "Deploy to dev"
          deployment: Dev
          script:
            - ssh -p 2200 root@113.176.195.87<<EOF
              /root/scripts/deploy-server.sh livechat-dev ${BITBUCKET_BUILD_NUMBER}
              exit
              exit
              EOF
              EOF
