image: node:10.15.3

pipelines:
  branches:
    dev:
      - step:
          caches:
            - node
          script:
            - ssh -p 2204 root@113.176.195.87<<EOF
              /vnlp/bitbucket/dev/livechat.sh
              exit
              exit
              EOF

