image: atlassian/default-image:2

pipelines:
  branches:
    dev:
      - step:
          name: "Build and push"
          image: atlassian/pipelines-awscli
          services:
            - docker
          script:
            - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 725359398979.dkr.ecr.ap-southeast-1.amazonaws.com
            - IMAGE="725359398979.dkr.ecr.ap-southeast-1.amazonaws.com/vnlp.server.livechat-dev"
            - VERSION="${BITBUCKET_BUILD_NUMBER}"
            - docker build -t ${IMAGE}:${VERSION} .
            - docker tag ${IMAGE}:${VERSION} ${IMAGE}:${VERSION}
            - docker push ${IMAGE}:${VERSION}
      - step:
          name: "Deploy to dev"
          deployment: Dev
          script:
            - ssh -p 2200 root@113.176.195.87<<EOF
              /root/scripts/deploy-server.sh livechat-dev ${VERSION}
              exit
              exit
              EOF
              EOF
